### ISSUE TITLE
Test case test-finite fails on Windows 10 with AttributeError: Can't pickle local object 'ParallelGenerator.__init__.<locals>.wrapped'

### ISSUE THREAD

**Issue by quaesitor-scientiam** [wetneb/multiprocessing_generator#9]
Running x64 Python 3.7.3

`test_bad_init (tests.tests.ParallelGeneratorTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.019s

OK
test_finite (tests.tests.ParallelGeneratorTest) ... ERROR
NoneType: None

======================================================================
ERROR: test_finite (tests.tests.ParallelGeneratorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\public\multiprocessing_generator\multiprocessing_generator\tests\tests.py", line 27, in test_finite
    with ParallelGenerator(l) as g:
  File "d:\public\multiprocessing_generator\multiprocessing_generator\generator\__init__.py", line 73, in __enter__
    self.process.start()
  File "c:\Python\python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "c:\Python\python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\Python\python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\Python\python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\Python\python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ParallelGenerator.__init__.<locals>.wrapped'

----------------------------------------------------------------------
Ran 1 test in 0.025s`

**Comment by wetneb** [comment]
Interesting! Maybe we should add Windows to the CI then. I am not so up to date about the difference in pickling between Linux and Windows, so any help with debugging this is most appreciated :)

**Comment by quaesitor-scientiam** [comment]
Core of the problem is this local function defined in the def __init__() of class ParallelGenerator

`        def wrapped():
            try:
                for item in orig_gen:
                    self.queue.put(item)
                raise StopIteration()
            except Exception as e:
                self.queue.put(ExceptionItem(e))
`

**Comment by quaesitor-scientiam** [comment]
Fixed it by moving that function to the global space and updated this line in the init()

`        self.process = Process(target=write, args=(orig_gen, self.queue))
`
reworked function
`def write(orig_gen, queue):
    try:
        for item in orig_gen:
            queue.put(item)
        raise StopIteration()
    except Exception as e:
        queue.put(ExceptionItem(e))
`

**Comment by quaesitor-scientiam** [comment]
Got other tests failing for the same pickling error do you want different issues for each one?  Log them all here?  My hope is this will help solve an issue preloading a queue with images and let be grabbed on demand.  My current solution gets an out of memory on long videos.  My attempts using maxsize with the queue also didn't work.

**Comment by wetneb** [comment]
No I think one issue is enough! And if you have a working solution, feel free to submit it as a pull request, so I can release it quickly. Thanks again for investigating this!

**Comment by quaesitor-scientiam** [comment]
Next error is test case: test_exception the first two are working.

`ERROR: test_exception (tests.tests.ParallelGeneratorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\public\multiprocessing_generator\multiprocessing_generator\tests\tests.py", line 41, in test_exception
    with ParallelGenerator(mygen()) as g:
  File "d:\public\multiprocessing_generator\multiprocessing_generator\generator\__init__.py", line 65, in __enter__
    self.process.start()
  File "c:\Python\python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "c:\Python\python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\Python\python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\Python\python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\Python\python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle generator objects
----------------------------------------------------------------------
Ran 1 test in 0.037s
FAILED (errors=1)`

This one I do not know how to solve.  Looks like have to punt on this being a solution.
